name: Deploy GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Add secrets & config file
        run: echo ${{ secrets.APPSETTINGS }} > wwwroot/appsettings.json

      - name: Build .NET Project
        run: dotnet build BlazorFileShake.csproj -c Release

      - name: Publish .NET Project
        run: |
          dotnet workload install wasm-tools
          dotnet publish BlazorFileShake.csproj -c Release -o publish

      - name: Copy 'index.html' to '404.html'
        run: cp publish/wwwroot/index.html publish/wwwroot/404.html

      - name: Add '.nojekyll' file
        run: touch publish/wwwroot/.nojekyll

      - name: Add 'CNAME' file
        run: echo 'bfs.subhamk.com' > publish/wwwroot/CNAME

      - name: Commit 'wwwroot' folder to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: publish/wwwroot
